# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6d87ab734ab4c449ac380af381e9e6502d7d735d70b741686473a1880e97eff7de8d6ad8a5849f1f0f7658d1c36a5e5a557b31b4ae0a63dcb3f365563b9577

test:
  secret_key_base: d7b341ee17420160354dc897b9a6b518adf1b7fd90232442d9ae3a60805847f1def6bf4c4f768124659cda40926404db0ed596f9a5a868d0554da540fa53e8d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
